# Generated by Django 4.1 on 2022-09-06 17:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userextend', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_year', models.IntegerField()),
                ('max_players', models.CharField(max_length=30)),
                ('best_players', models.IntegerField()),
                ('playtime', models.CharField(max_length=30)),
                ('player_age', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('designer', models.CharField(max_length=200)),
                ('artists', models.CharField(max_length=200)),
                ('language_dependence', models.CharField(max_length=200)),
                ('description', models.TextField(default=None, max_length=500)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('area_control', 'Area Control'), ('campaign/legacy', 'Campaign/Legacy'), ('cooperative', 'Cooperative'), ('deckbuilder', 'Deckbuilder'), ('dexterity', 'Dexterity'), ('drafting', 'Drafting'), ('dungeon_crawler', 'Dungeon-crawler'), ('engine_builder', 'Engine-builder'), ('eurogame', 'Eurogame'), ('push_your_luck', 'Push-your-luck'), ('resource_management', 'Resource Management'), ('roll_and_move', 'Roll-and-move'), ('roll_and_write', 'Roll-and-write'), ('role_playing_game', 'RPG - Role-Playing Game'), ('social_deduction', 'Social deduction'), ('storytelling', 'Storytelling'), ('worker_placement', 'Worker-placement'), ('wargame', 'Wargame')], max_length=200, null=True), size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animals', 'Animals'), ('bluffing', 'Bluffing'), ('card_game', 'Card Game'), ('childrens_game', 'Children"s Game'), ('city_building', 'City Building'), ('civilization', 'Civilization'), ('dice', 'Dice'), ('educational', 'Educational'), ('environmental', 'Environmental'), ('expansion_for_basegame', 'Expention for Base-game'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('memory', 'Memory'), ('murder/mystery', 'Murder/Mystery'), ('negotiation', 'Negotiation'), ('party_game', 'Party Game'), ('puzzle', 'Puzzle'), ('science_fiction', 'Science Fiction'), ('sports', 'Sports'), ('strategy', 'Strategy'), ('travel', 'Travel'), ('trivia', 'Trivia'), ('war', 'War'), ('word_game', 'Word Game'), ('zombies', 'Zombies')], max_length=200, null=True), size=None)),
                ('mechanics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[], max_length=200, null=True), size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userextend.userextend')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardgames', to='userextend.userextend')),
            ],
        ),
    ]
