# Generated by Django 4.1 on 2022-09-06 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='mechanics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[], max_length=200, null=True), default=list, size=None),
        ),
    ]
