# Generated by Django 4.1 on 2022-09-11 05:20

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_alter_boardgame_mechanics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='categories',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animals', 'Animals'), ('bluffing', 'Bluffing'), ('card_game', 'Card Game'), ('childrens_game', 'Children"s Game'), ('city_building', 'City Building'), ('civilization', 'Civilization'), ('dice', 'Dice'), ('educational', 'Educational'), ('environmental', 'Environmental'), ('expansion_for_basegame', 'Expention for Base-game'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('memory', 'Memory'), ('murder/mystery', 'Murder/Mystery'), ('negotiation', 'Negotiation'), ('party_game', 'Party Game'), ('puzzle', 'Puzzle'), ('science_fiction', 'Science Fiction'), ('sports', 'Sports'), ('strategy', 'Strategy'), ('travel', 'Travel'), ('trivia', 'Trivia'), ('war', 'War'), ('word_game', 'Word Game'), ('zombies', 'Zombies')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='mechanics',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('luck', 'Luck')], max_length=200, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='types',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('area_control', 'Area Control'), ('campaign/legacy', 'Campaign/Legacy'), ('cooperative', 'Cooperative'), ('deckbuilder', 'Deckbuilder'), ('dexterity', 'Dexterity'), ('drafting', 'Drafting'), ('dungeon_crawler', 'Dungeon-crawler'), ('engine_builder', 'Engine-builder'), ('eurogame', 'Eurogame'), ('push_your_luck', 'Push-your-luck'), ('resource_management', 'Resource Management'), ('roll_and_move', 'Roll-and-move'), ('roll_and_write', 'Roll-and-write'), ('role_playing_game', 'RPG - Role-Playing Game'), ('social_deduction', 'Social deduction'), ('storytelling', 'Storytelling'), ('worker_placement', 'Worker-placement'), ('wargame', 'Wargame')], max_length=200, null=True), size=None),
        ),
    ]
