# Generated by Django 4.1 on 2022-09-11 06:02

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_alter_boardgame_categories_alter_boardgame_mechanics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='categories',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animals', 'Animals'), ('bluffing', 'Bluffing'), ('card_game', 'Card Game'), ('childrens_game', 'Children"s Game'), ('city_building', 'City Building'), ('civilization', 'Civilization'), ('dice', 'Dice'), ('educational', 'Educational'), ('environmental', 'Environmental'), ('expansion_for_basegame', 'Expansion for Base-game'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('memory', 'Memory'), ('murder/mystery', 'Murder/Mystery'), ('negotiation', 'Negotiation'), ('party_game', 'Party Game'), ('puzzle', 'Puzzle'), ('science_fiction', 'Science Fiction'), ('sports', 'Sports'), ('strategy', 'Strategy'), ('travel', 'Travel'), ('trivia', 'Trivia'), ('war', 'War'), ('word_game', 'Word Game'), ('zombies', 'Zombies')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='mechanics',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('action_drafting', 'Action Drafting'), ('action_points', 'Action Points'), ('action_timer', 'Action Timer'), ('alliances', 'Alliances'), ('area_majority', 'Aria Majority'), ('area_movement', 'Area Movement'), ('area_control', 'Area Control'), ('card_drafting', 'Card Drafting'), ('hand_management', 'Hand Management'), ('auction_bidding', 'Auction/Biddig'), ('betting_bluffing', 'Betting and Bluffing'), ('campaign_battle_card_driven', 'Campagn/Battle Card Driven'), ('closed_drafting', 'Closed Drafting'), ('cooperative_game', 'Cooperative Game'), ('deck_construction', 'Deck Construction'), ('dice_rolling', 'Dice Rolling'), ('drawing', 'Drawing'), ('grid_movement', 'Grid Movement'), ('hand_management', 'Hand Management'), ('hidden_roles', 'Hidden Roles'), ('hot_potato', 'Hot Potato'), ('i_cut_you_choose', 'I cut you Choose'), ('investment', 'Investment'), ('ladder_climbing', 'Ladder Climbing'), ('layering', 'Layering'), ('legacy_game', 'Legacy Game'), ('pattern_recognition', 'Pattern Recognition'), ('pick_up_and_deliver', 'Pick-up nad Deliver'), ('player_elimination', 'Player Elimination'), ('point2point_movement', 'Point-to-Point Movement'), ('push_your_luck', 'Push Your Luck'), ('real_time', 'Real Time'), ('route_building', 'Route Building'), ('set_collecting', 'Set Collecting'), ('story_telling', 'Story Telling'), ('social_deduction', 'Social Deduction'), ('take_that', 'Take that'), ('tile_placement', 'Tile Placement'), ('worker_placement', 'Worker Placement')], max_length=200, null=True), default=list, size=None),
        ),
    ]
