# Generated by Django 4.1 on 2022-09-18 22:17

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0002_userprofile'),
        ('boardgames', '0007_alter_boardgame_categories_alter_boardgame_mechanics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='categories',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Action', 'action'), ('Adventure', 'adventure'), ('Abstract Strategy', 'abstract_strategy'), ('Animals', 'animals'), ('Bluffing', 'bluffing'), ('Card Game', 'card_game'), ('Children"s Game', 'childrens_game'), ('City Building', 'city_building'), ('Civilization', 'civilization'), ('Dice', 'dice'), ('Educational', 'educational'), ('Environmental', 'environmental'), ('Expansion for Base-game', 'expansion_for_basegame'), ('Fantasy', 'fantasy'), ('Historical', 'historical'), ('Horror', 'horror'), ('Memory', 'memory'), ('Murder/Mystery', 'murder/mystery'), ('Negotiation', 'negotiation'), ('Party Game', 'party_game'), ('Puzzle', 'puzzle'), ('Science Fiction', 'science_fiction'), ('Sports', 'sports'), ('Strategy', 'strategy'), ('Travel', 'travel'), ('Trivia', 'trivia'), ('War', 'war'), ('Word Game', 'word_game'), ('Zombies', 'zombies')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='mechanics',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Action Drafting', 'action_drafting'), ('Action Points', 'action_points'), ('Action_timer', 'Action Timer'), ('Alliances', 'alliances'), ('Aria Majority', 'area_majority'), ('Area Movement', 'area_movement'), ('Area Control', 'area_control'), ('Card Drafting', 'card_drafting'), ('Hand Management', 'hand_management'), ('Auction/Bidding', 'auction_bidding'), ('Betting and Bluffing', 'betting_bluffing'), ('Campaign/Battle Card Driven', 'campaign_battle_card_driven'), ('Open Drafting', 'open_drafting'), ('Closed Drafting', 'closed_drafting'), ('Cooperative Game', 'cooperative_game'), ('Deck construction', 'deck_construction'), ('Dice Rolling', 'dice_rolling'), ('Drawing', 'drawing'), ('Grid Movement', 'grid_movement'), ('Hand Management', 'hand_management'), ('Hidden Roles', 'hidden_roles'), ('Hot Potato', 'hot_potato'), ('I cut you Choose', 'i_cut_you_choose'), ('Investment', 'investment'), ('Ladder Climbing', 'ladder_climbing'), ('Layering', 'layering'), ('Legacy game', 'legacy_game'), ('Pattern Recognition', 'pattern_recognition'), ('Pattern Building', 'pattern_building'), ('Pick-up nad Deliver', 'pick_up_and_deliver'), ('Square Grid', 'square_grid'), ('Player Elimination', 'player_elimination'), ('Point-to-Point Movement', 'point2point_movement'), ('Push Your Luck', 'push_your_luck'), ('Real Time', 'real_time'), ('Route Building', 'route_building'), ('Set Collecting', 'set_collecting'), ('Story Telling', 'story_telling'), ('Social Deduction', 'social_deduction'), ('Take that', 'take_that'), ('Tile Placement', 'tile_placement'), ('Worker Placement', 'worker_placement')], max_length=200, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='types',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Abstract', 'abstract'), ('Area Control', 'area_control'), ('Campaign/Legacy', 'campaign/legacy'), ('Cooperative', 'cooperative'), ('Deckbuilder', 'deckbuilder'), ('Dexterity', 'dexterity'), ('Drafting', 'drafting'), ('Dungeon Crawler', 'dungeon_crawler'), ('Engine Builder', 'engine_builder'), ('Eurogame', 'eurogame'), ('Family', 'family'), ('Push your luck', 'push-your-luck'), ('Resource Management', 'resource_management'), ('Roll-and-move', 'roll_and_move'), ('Roll-and-write', 'roll_and_write'), ('Family', 'family'), ('RPG - Role-Playing Game', 'role_playing_game'), ('Social deduction', 'social_deduction'), ('Strategy', 'strategy'), ('Party', 'party'), ('Storytelling', 'storytelling'), ('Worker-placement', 'worker_placement'), ('Wargame', 'wargame')], max_length=200, null=True), size=None),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardgames.boardgame')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend')),
            ],
        ),
    ]
