# Generated by Django 4.1 on 2022-09-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0011_alter_boardgame_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgamecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='boardgamecomment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
    ]
