# Generated by Django 4.1 on 2022-09-20 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0012_alter_boardgamecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecomment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.CreateModel(
            name='BoardgameInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular game across whole library', primary_key=True, serialize=False)),
                ('specifics', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'On Loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Boardgame availability', max_length=1)),
                ('boardgame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='boardgames.boardgame')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
